title: Prudhviraj Panisetti
logo: /assets/Img/Profile.jpg
description: Full stack Python developer
#show_downloads: false
#theme: jekyll-theme-minimal #https://pages.github.com/themes/
theme: prudhvirajstark/minimal-Jekyll
